accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('doctors/', views.doctors_list, name='doctors_list'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('<slug:slug>/', views.doctors_detail, name='doctors_detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace ='accounts')),
]


if settings.DEBUG is True:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.utils.text import slugify

TYPE_OF_PERSON = (
    ('M',"Male"),
    ('F',"Female"),
)


# Create your models here.
class Profile(models.Model):
    """Model definition for Profile."""
    
    DIR_IN = {
        ('طب الأطفال',"طب الأطفال"),
        ('طب الأنف والأذن والحنجرة',"طب الأنف والأذن والحنجرة"),
        ('طب التوليد والنسائيات',"طب التوليد والنسائيات"),
        ('طب الجهاز البولي',"طب الجهاز البولي"),
        ('طب الطوارئ',"طب الطوارئ"),
        ('طب الطوارئ الدولي',"طب الطوارئ الدولي"),
        ('طب العيون',"طب العيون"),
        ('طب باطني',"طب باطني"),
        ('أسنان',"أسنان"),

    }
    
    user  = models.OneToOneField( User, verbose_name=_("user"), on_delete=models.CASCADE)
    name = models.CharField(_("الاسم: "), max_length=50)
    subtitle = models.CharField(_("نبذه عنك: "), max_length=50)
    adress = models.CharField(_("المحافظة: "), max_length=50)
    adress_details = models.CharField(_("العنوان بالتفصيل: "), max_length=50)
    phone_number = models.CharField(_("الهاتف"), max_length=50)
    working_hours = models.CharField(_("عدد ساعات العمل: "), max_length=50)
    waiting_time = models.IntegerField(_("مدة الانتظار "),blank=True, null=True)
    doctor_specialist = models.CharField(_("متخصص في؟"), max_length=50,blank=True, null=True)
    who_i = models.TextField(_("من أنا: "), max_length=50)
    price = models.IntegerField(_("سعر الكشف"),blank=True, null=True)
    facebook = models.CharField(max_length=50,blank=True, null=True)
    twittre = models.CharField(max_length=50,blank=True, null=True)
    google = models.CharField(max_length=50,blank=True, null=True)
    join_new = models.DateField(_("وقت الإنضمام :"), auto_now_add=True)
    type_of_person = models.CharField(_("النوع"),choices=TYPE_OF_PERSON, max_length=50)
    image = models.ImageField(_("الصورة الشخصية"), upload_to='profile',blank=True, null=True)
    slug = models.SlugField(_("slug"), blank=True, null=True)
    doctor = models.CharField(_("دكتور ؟"),choices=DIR_IN, max_length=50,blank=True, null=True)
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        
        super(Profile,self).save(*args,**kwargs)
    # TODO: Define fields here

    class Meta:
        """Meta definition for Profile."""

        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        """Unicode representation of Profile."""
        return '%s' %(self.user.username)


def creat_profile(sender, **kwargs):
    
    if kwargs['created']:
        Profile.objects.create(user = kwargs['instance'])


post_save.connect(creat_profile, sender= User)      

    # TODO: Define custom methods here

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreationForms(UserCreationForm):
        username = forms.CharField(label='اسم المستخدم ')
        first_name = forms.CharField(label = 'الاسم الاول')
        last_name = forms.CharField(label = 'الاسم الاخير')
        email = forms.EmailField(label = 'البريد الالكتروني')
        password1 = forms.CharField(label='كلمة المرور ', widget=forms.PasswordInput(), min_length=8)
        password2 = forms.CharField(label='تأكيد كلمة المرور  ', widget=forms.PasswordInput(), min_length=8)


        class Meta:
            model = User
            fields = ('username', 'password1','first_name','last_name','email','password2' )




class Login_Form(forms.ModelForm):
    username = forms.CharField(label='الاسم ')
    password = forms.CharField(label='كلمة المرور ', widget=forms.PasswordInput(), min_length=8)

    class Meta:
        model = User
        fields = ('username', 'password' )





class UpdateUserForm(forms.ModelForm):

    first_name = forms.CharField(label = 'الاسم الاول')
    last_name = forms.CharField(label = 'الاسم الاخير')
    email = forms.EmailField(label = 'البريد الالكتروني')


    class Meta:
        model = User
        fields = ('first_name','last_name','email')

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import Profile
from .forms import Login_Form, UserCreationForms, UpdateUserForm
from django.contrib.auth import  authenticate, login
from django.contrib.auth.decorators import login_required

# Create your views here.
def doctors_list(request):
    doctors = User.objects.all() # Query set

    return render(request, 'user/doctors_list.html', {'doctors': doctors })


def doctors_detail(request, slug):
    doctors_detail = Profile.objects.get(slug = slug) # Query set

    return render(request, 'user/doctors_detail.html', {'doctors_detail': doctors_detail })



def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request,user)
            return redirect('accounts:doctors_list')

    else:
        form = Login_Form()

    return render(request, 'user/login.html', {'form': form })

def signup(request):
    if request.method == 'POST':
       form = UserCreationForms(request.POST)
       if form.is_valid():
           form.save()
           username = form.cleaned_data.get('username')
           password = form.cleaned_data.get('password')
           user = authenticate(username = username, password = password)
           login(request,user)
           return redirect('accounts:doctors_list')
    else:
        form = UserCreationForms()

    return render(request, 'user/signup.html', {'form': form })


@login_required()
def myprofile(request):

    user_form = UpdateUserForm(instance= request.user)
    return render(request, 'user/update_profile.html', {'user_form':user_form})




def update_profile(request):

    user_form = UpdateUserForm(instance=request.user)

    if request.method == "POST":
            user_form = UpdateUserForm(request.POST,instance=request.user)
            if user_form.is_valid():
                user_form.save()
                return redirect('accounts:doctors_list')


    return render(request, 'user/update_profile.html', {'user_form':user_form})

accounts/templates/user/doctors_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


<div dir="rtl">
    {% include "user/search.html" %}
    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    {% for doctor in doctors  %}
                      
                   
                    <div class="col-lg-10 col-md-10" style="height: 16rem;" >
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div >
                                        
                                        {% if doctor.profile.image %}

                                         <img  src="{{ doctor.profile.image.url }}" alt="" width="100" height="100">

                                        {% else %}

                                         <img  src="{% static 'static_files/img/candiateds/1.png'%}" alt="" width="100" height="100">

                                        {% endif %}
                                        
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'accounts:doctors_detail' doctor.profile.slug %}"><h5>{{ doctor.profile.name }} دكتور </h5></a>
                                    <h6>{{ doctor.profile.subtitle }} </h6>
                                    
                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;">{{ doctor.profile.doctor }} </span> متخصص في <span style="color: blue;">{{ doctor.profile.doctor_specialist}}</span></p>
                                            <p> <i class="fa fa-map-marker"></i>العنوان : {{ doctor.profile.adress_details }} </p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;">{{ doctor.profile.price }} </span> جنية</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">{{ doctor.profile.waiting_time }} </span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{ doctor.profile.working_hours }} </span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> {{ doctor.profile.phone_number }}  </span>  </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="">حجز كشف</a>
                                </div>

                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        </div>
                                    <div class="rating" >
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                       
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="{% static 'static_files/img/candiateds/2.png' %}" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- featured_candidates_area_end  -->
    
{% endblock body %}

accounts/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}



<div dir="rtl">
    <div class="container">
        <div class="signup">
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                <h4 class="auth-header">تسجيل الدخول</h4>
                    {% csrf_token %}
                <div class="form-group">
                   {{ form.username|as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password|as_crispy_field }}
                </div>
                <div class="buttons-w  "><button type="submit" class="btn btn-success ml-5">تسجيل</button>
               
            </div>
            </form>
        </div>
        </div>
    </div>
    </div>


{% endblock body %}

accounts/templates/user/search.html
<!-- Search -->
<div class="catagory_area ">
    <div class="container " style="margin-top: 10rem">
                <div class=" single_text">
                    <h2>احجز مع
                        أفضل دكتور في مصر</h3>
                    <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                    <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                    <br>
                </div>
                <form  method="GET" action="">
                <div class="row cat_search" >
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <input type="text" placeholder="إسم الدكتور" >
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="" >الموقع</option>
                                <option value="المنصوره">المنصوره</option>
                                <option value="الدقي">الدقي</option>
                                <option value="4">Sylet</option>
                            </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="">التخصص</option>
                                <option value="جلدية">جلدية</option>
                                <option value="اسنان">اسنان</option>
                                <option value="نفسي">نفسي</option>
                                <option value="اطفال">اطفال حديثي الولادة</option>
                                <option value="مخ">مخ واعصاب</option>
                                <option value="عظام">عظام</option>
                                <option value="نساء">نساء وتوليد</option>
                                <option value="انف">انف واذن وحنجرة</option>
                                <option value="قلب">قلب واوعية دموية</option>
                                <option value="امراض">امراض دم</option>
                                <option value="اورام">اورام</option>
                                <option value="باطنه">باطنه</option>
                                <option value="تخسيس">تخسيس وتغذية</option>
                                <option value="جاطفال">جراحة اطفال</option>
                                <option value="جاورام">جراحة اورام</option>
                                <option value="جاوعيه">جراحة اوعية دموية</option>
                                <option value="جتجميل">جراحة تجميل</option>
                                <option value="سمنه">جراحه سمنة ومناظير </option>
                                </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-12">
                        <div class="job_btn">
                            <input type="submit" class="boxed-btn3" value="ابحث هنا">
                        </div>
                    </div>
    
                </div>
                </form> 
            </div>
        </div>
        <!-- endsearch -->

accounts/templates/user/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}


<div dir="rtl">
    <div class="container">
        <div class="signup">

        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                <h4 class="auth-header">أنشاء حساب جديد: </h4>
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username|as_crispy_field }}
                </div>
                <div class="form-group">
                      {{ form.email|as_crispy_field }}

                </div>
                <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                            {{ form.first_name|as_crispy_field }}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                            {{ form.last_name|as_crispy_field }}
                      </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                            {{ form.password1|as_crispy_field }}
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                            {{ form.password2|as_crispy_field }}
                      </div>
                    </div>

                </div>

                <div class="buttons-w"><button type="submit" class="btn btn-success">التسجيل</button></div>

            </form>
        </div>
        </div>
    </div>
    </div>




















{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'static_files/img/favicon.png' %} ">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'static_files/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'static_files/css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'static_files/css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>
<body>

    <!-- header-start -->
    <header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
                <div class="header_bottom_border">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="index.html">
                                    <img src="{% static 'static_files/img/logo2.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{% url 'accounts:doctors_list'%}">احجز دكتورك</a></li>|
                                        <li><a href="">المقالات</a></li>|
                                        <li><a href="{% url 'accounts:myprofile'%}">الصفحه الشخصيه </a></li>|
                                        <li><a href="contact.html">اتصل بنا</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                
                                
                                {% if user.is_authenticated %}

                                    <div class="phone_num d-none d-xl-block"></div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="">قدم نفسك</a>
                                    </div>
                                {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a class="boxed-btn3" href="{% url 'accounts:login'%}">تسجيل الدخول</a>
                                    </div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" style="background-color: crimson;" href="{% url 'accounts:signup'%}">التسجيل</a>
                                    </div>
                                {% endif %}
                                
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
    
            </div>
        </div>
    </div>
    </header>
    <!-- header-end -->
 
 {% block body %}
   
 {% endblock body %}


<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                    <div class="footer_logo">
                        <a href="#">
                            <img src="{% static 'static_files/img/logo2.png' %}" alt="">
                        </a>
                    </div>
                    <p>
                        ma7mod.raouf@gmail.com <br>
                        +01005162422 <br>
                        Mansora, Egypt
                    </p>
                    <div class="socail_links">
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/m7modsabra">
                                    <i class="ti-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/channel/UC7FFcZc90vE5FfR_dgA_dVg?view_as=subscriber">
                                    <i class="fa fa-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                    <h3 class="footer_title">
                        ماذا عنا
                    </h3>
                    <ul>
                        <li><a href="https://code4learn.teachable.com/p/online-courses">من نحن </a></li>
                        <li><a href="https://code4learn.teachable.com/p/online-courses"> أسعارنا</a></li>
                        <li><a href="https://www.facebook.com/m7modsabra">إستفسار</a></li>
                    </ul>
    
                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                    <h3 class="footer_title">
                        الخدمات
                    </h3>
                    <ul>
                        <li><a href="https://code4learn.teachable.com/p/soundcloud">اعمالنا</a></li>
                        <li><a href="https://twitter.com/code4learn/status/1236082742582001670?s=21">شركائنا</a></li>
                        <li><a href="https://code4learn.teachable.com/p/online-courses">الخصومات والمشاريع</a></li>
                        <li><a href="https://www.facebook.com/m7modsabra">للإعلان</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                    <h3 class="footer_title">
                        Subscribe
                    </h3>
                    <form action="#" class="newsletter_form">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                        luckily.</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
    <div class="container">
        <div class="footer_border"></div>
        <div class="row">
            <div class="col-xl-12">
                <p class="copy_right text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'static_files/js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'static_files/js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'static_files/js/popper.min.js'%}"></script>
    <script src="{% static 'static_files/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'static_files/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'static_files/js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'static_files/js/ajax-form.js'%}"></script>
    <script src="{% static 'static_files/js/waypoints.min.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'static_files/js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'static_files/js/scrollIt.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'static_files/js/wow.min.js'%}"></script>
    <script src="{% static 'static_files/js/nice-select.min.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'static_files/js/plugins.js'%}"></script>
    <script src="{% static 'static_files/js/gijgo.min.js'%}"></script>
    
    
    
    <!--contact js-->
    <script src="{% static 'static_files/js/contact.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.form.js'%}"></script>
    <script src="{% static 'static_files/js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'static_files/js/mail-script.js'%}"></script>
    
    
    <script src="{% static 'static_files/js/main.js'%}"></script>
    </body>
    
    </html>